version: 2.1
orbs:
  node: circleci/node@5.0.1
jobs:
  end-to-end:
    docker:
      - image: mcr.microsoft.com/playwright:v1.24.2-focal
    environment:
      NODE_ENV: development
      VERCEL_URL: https://alpha.wiserfunding.com/login
      PLAYWRIGHT_LOGIN_USERNAME: jack@antler.digital
      PLAYWRIGHT_LOGIN_PASSWORD: Password1!

    working_directory: ~/wiserfunding
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: npx playwright install-deps
      - run:
          name: Setup
          command: |
            yarn install
            npx playwright install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: E2E
          command: yarn playwright

workflows:
  end-to-end:
    jobs:
      - end-to-end
