version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build-and-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.24.2-focal
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: npm run lint -- --format junit -o reports/junit/js-lint-results.xml
      - run:
          name: Test
          command: npm run test:coverage
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage

workflows:
  build-and-test:
    jobs:
      - build-and-test:
          context: SonarCloud
