import { ErrorCodeKeys } from '../../types/errors';

export const UNAUTHORISED: ErrorCodeKeys = 'UNAUTHORISED';
export const UNPROCESSABLE_ENTITY: ErrorCodeKeys = 'UNPROCESSABLE_ENTITY';
export const NO_REPORT_ID: ErrorCodeKeys = 'NO_REPORT_ID';
export const SIGNED_OUT: ErrorCodeKeys = 'SIGNED_OUT';
export const USER_404: ErrorCodeKeys = 'USER_404';
export const USER_403: ErrorCodeKeys = 'USER_403';
export const USER_422: ErrorCodeKeys = 'USER_422';
export const USER_500: ErrorCodeKeys = 'USER_500';
export const COMPANY_404: ErrorCodeKeys = 'COMPANY_404';
export const COMPANY_422: ErrorCodeKeys = 'COMPANY_422';
export const COMPANY_500: ErrorCodeKeys = 'COMPANY_500';
export const NO_REPORT: ErrorCodeKeys = 'NO_REPORT';
export const NO_REPORT_FOUND: ErrorCodeKeys = 'NO_REPORT_FOUND';
export const REPORT_FETCHING_ERROR: ErrorCodeKeys = 'REPORT_FETCHING_ERROR';
export const BATCH_REPORT_FETCHING_ERROR: ErrorCodeKeys =
  'BATCH_REPORT_FETCHING_ERROR';
export const GENERIC_API_ERROR: ErrorCodeKeys = 'GENERIC_API_ERROR';
export const GENERIC_API_ERROR_FORM: ErrorCodeKeys = 'GENERIC_API_ERROR_FORM';
export const VALID_EMAIL_REQUIRED: ErrorCodeKeys = 'VALID_EMAIL_REQUIRED';
export const EMAIL_REQUIRED: ErrorCodeKeys = 'EMAIL_REQUIRED';
export const INVALID_SSO_LOGIN: ErrorCodeKeys = 'INVALID_SSO_LOGIN';
export const PASSWORD_REQUIRED: ErrorCodeKeys = 'PASSWORD_REQUIRED';
export const INCORRECT_DETAILS: ErrorCodeKeys = 'INCORRECT_DETAILS';
export const FULL_NAME_REQUIRED: ErrorCodeKeys = 'FULL_NAME_REQUIRED';
export const NEW_PASSWORD_REQUIRED: ErrorCodeKeys = 'NEW_PASSWORD_REQUIRED';
export const CONFIRM_PASSWORD_MATCH: ErrorCodeKeys = 'CONFIRM_PASSWORD_MATCH';
export const SEARCH_ERROR: ErrorCodeKeys = 'SEARCH_ERROR';
export const INVALID_COUNTRY_CODE: ErrorCodeKeys = 'INVALID_COUNTRY_CODE';
export const COUNTRY_CODE_REQUIRED: ErrorCodeKeys = 'COUNTRY_CODE_REQUIRED';
export const COMPANY_NAME_REQUIRED: ErrorCodeKeys = 'COMPANY_NAME_REQUIRED';
export const COMPANY_WEBSITE_REQUIRED: ErrorCodeKeys =
  'COMPANY_WEBSITE_REQUIRED';
export const INVALID_REQUEST_TYPE: ErrorCodeKeys = 'INVALID_REQUEST_TYPE';
export const METHOD_NOT_ALLOWED: ErrorCodeKeys = 'METHOD_NOT_ALLOWED';
export const MISSING_DATA: ErrorCodeKeys = 'MISSING_DATA';
export const NO_COMPANY_ID: ErrorCodeKeys = 'NO_COMPANY_ID';
export const NO_CURRENCY: ErrorCodeKeys = 'NO_CURRENCY';
export const NO_ISO_CODE: ErrorCodeKeys = 'NO_ISO_CODE';
export const VALIDATION_ERROR: ErrorCodeKeys = 'VALIDATION_ERROR';
